title: Anna-Janina Goecke # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Position <br />
  NLP Engineer and Researcher <br />
  MSc. Cognitive Systems <br />
  <br />
  About Me <br />
  Add Description Text here <br />
  
  <a href="https://www.linkedin.com/in/ajgoecke/">View My LinkedIn Profile</a> <br />
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# your Google Analytics tracking ID here
