title: Anna-Janina Goecke # your name (or website title) here
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  NLP Engineer and Researcher <br />
  MSc. Cognitive Systems Graduate <br />
  <br />
  About Me <br />
  Graduate of MSc. Cognitive Systems with experience in software development for Natural Language Processing tasks and (text) data analysis. 
  My most recent project is the implementation of NLP tools to generate definition texts for a discourse glossry.<br />
  
 
  
  <a href="https://www.linkedin.com/in/ajgoecke/">View My LinkedIn Profile</a> <br />
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# your Google Analytics tracking ID here
